service: EmailService

frameworkVersion: ">=1.17.0 <2.0.0"

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs8.10
  memorySize: 512
  timeout: 300 # 5 minutes (maxium allowed)
  deploymentBucket:
    name: sumofus.org.serverless.us-west-2
  environment:
    MAILINGS_TABLE: ${self:service}-Mailings-${opt:stage, self:provider.stage}
    SENDGRID_API_KEY: ${opt:sendgrid_api_key}
    REGION: ${opt:aws_region, self:provider.region}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:provider.environment.MAILINGS_TABLE}"
functions:
  mailer:
    handler: functions/mail/index.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - MailingsTable
              - StreamArn
          batchSize: 10
          startingPosition: LATEST

resources:
  Resources:
    MailingsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: MailingId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: MailingId
            KeyType: HASH
          - AttributeName: UserId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        TableName: ${self:provider.environment.MAILINGS_TABLE}
